# Generated by Django 3.0.3 on 2020-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='portfolio/images')),
                ('URL', models.URLField(blank=True)),
            ],
        ),
    ]
